### ISSUE TITLE
김경태 계획

### ISSUE THREAD

**Issue by hakumaku** [hakumaku/reggae_chicken#3]
### Learning Python
- 이미 다 봄
### Head First HTML
- 진행중 (완 03.09)
### CSS the missing manual
- 진행중 (완 03.11)
###### <caption>( *16 chapter)
- 배우는데 시간 오래걸릴 듯(약 1000페이지, 500페이지 정도는 15일까지 무난하게 가능)
### Django
- 설치 / 환경 구축 해보고, 샘플 코드 몇개 작성해봄, 웹언어 필요해서 잠시 중지.

**Comment by hooon2y** [comment]
Javascript the definitive guide

배우는데 시간 오래걸릴 듯 <---------- 이런건 계획을 좀 더 잘게 쪼개서 이번주에 할 수 있는 챕터? 를 적어주면 더 좋을듯여

**Comment by hakumaku** [comment]
네, Learning Python이랑 두깨가 비슷해서, 이게 2주 걸렸거든요, 어림짐작 2주는 잡아야 하지 않을까.. 근데 쉽다고들 하니깐, 또 금방할꺼 같기도 하고

**Comment by hooon2y** [comment]
네 그래서 쪼개서 일주일치만 올려줘요
(1 / 2) 이런식으로
